blank_issues_enabled: false
contact_links:
  - name: "Questions or Support"
    url: https://github.com/PulseInjector/linklike/discussions
    about: "Ask questions or get help in Discussions"
  - name: "Security Issue"
    url: https://github.com/PulseInjector/linklike/security/policy
    about: "Report a security vulnerability safely"
